# Site wide configuration

title: Write, Review, Test, Merge, Build, Deploy, Repeat. <br> Let's Treat Docs Like Code
locale: en-US
description: When you want to write more content, create accurate technical docs, iterate with collaborators, test drafts, merge, build, and deploy docs.
logo: /images/treat-docs-like-code.png
#url: http://127.0.0.1:4000
url: https://www.docslikecode.com
theme: jekyll-theme-so-simple
search_full_content: true
tag_archive_path: "/tags/#"
footer_links:
  - title: Twitter
    url: https://twitter.com/annegentle
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/justwriteclick
    icon: fab fa-github-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-85706588-1
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["_drafts", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: false
twitter: annegentle
google_analytics: UA-85706588-1

# Site author, previously was site.owner
author:
  name: Anne Gentle
  picture: /images/anne_gentle.jpg
  email: annegentle@justwriteclick.com
  disqus-shortname:
  facebook:
  github: justwriteclick
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  pinterest:
  weibo:
  google:
    plus: AnneGentle
    verify: LDMHcKG0vxyyo7Tp6hA5xs3_lJYX7Spk9IqC4VZsitE
    ad-client:
    ad-slot:
  bing-verify:
